/**
 * Created by Vadym Yatsyuk on 06/03/16
 */
export const UPDATE_PLAYER_POSITION = 'UPDATE_PLAYER_POSITION';
export const UPDATE_MAP_CLEAR = 'UPDATE_MAP_CLEAR';
export const UPDATE_PLAYER_HEALTH = 'UPDATE_PLAYER_HEALTH';
export const UPDATE_PLAYER_WEAPON = 'UPDATE_PLAYER_WEAPON';
export const UPDATE_PLAYER_EXPERIENCE = 'UPDATE_PLAYER_EXPERIENCE';
export const UPDATE_PLAYER_LEVEL = 'UPDATE_PLAYER_LEVEL';
export const UPDATE_PLAYER_MAX_EXPERIENCE = 'UPDATE_PLAYER_MAX_EXPERIENCE';
export const UPDATE_PLAYER_SET_DEFAUL = 'UPDATE_PLAYER_SET_DEFAUL';
export const UPDATE_MAP_BLOCK = 'UPDATE_MAP_BLOCK';
export const UPDATE_MAP_RESET = 'UPDATE_MAP_RESET';
export const CHANGE_LEVEL = 'CHANGE_LEVEL';
export const UPDATE_MODAL = 'UPDATE_MODAL';
export const UPDATE_DARKNESS = 'UPDATE_DARKNESS';
export const UPDATE_PLAYER_DIRECTION = 'UPDATE_PLAYER_DIRECTION';
